export declare const DEFAULT_SPLIT_STATE_SLICE = "splitio";
export declare const VERSION: string;
export declare const ON: SplitIO.Treatment;
export declare const OFF: SplitIO.Treatment;
export declare const CONTROL: SplitIO.Treatment;
export declare const CONTROL_WITH_CONFIG: SplitIO.TreatmentWithConfig;
export declare const getControlTreatmentsWithConfig: (featureFlagNames: string[]) => SplitIO.TreatmentsWithConfig;
export declare const SPLIT_READY = "SPLIT_READY";
export declare const SPLIT_READY_WITH_EVALUATIONS = "SPLIT_READY_WITH_EVALUATIONS";
export declare const SPLIT_READY_FROM_CACHE = "SPLIT_READY_FROM_CACHE";
export declare const SPLIT_READY_FROM_CACHE_WITH_EVALUATIONS = "SPLIT_READY_FROM_CACHE_WITH_EVALUATIONS";
export declare const SPLIT_UPDATE = "SPLIT_UPDATE";
export declare const SPLIT_UPDATE_WITH_EVALUATIONS = "SPLIT_UPDATE_WITH_EVALUATIONS";
export declare const SPLIT_TIMEDOUT = "SPLIT_TIMEDOUT";
export declare const SPLIT_DESTROY = "SPLIT_DESTROY";
export declare const ADD_TREATMENTS = "ADD_TREATMENTS";
export declare const ERROR_GETT_NO_INITSPLITSDK = "[ERROR] To use \"getTreatments\" the SDK must be first initialized with an \"initSplitSdk\" action";
export declare const ERROR_DESTROY_NO_INITSPLITSDK = "[ERROR] To use \"destroySplitSdk\" the SDK must be first initialized with an \"initSplitSdk\" action";
export declare const ERROR_TRACK_NO_INITSPLITSDK = "[ERROR] To use \"track\" the SDK must be first initialized with an \"initSplitSdk\" action";
export declare const ERROR_MANAGER_NO_INITSPLITSDK = "[ERROR] To use the manager, the SDK must be first initialized with an \"initSplitSdk\" action";
export declare const ERROR_SELECTOR_NO_SPLITSTATE = "[ERROR] When using selectors, \"splitState\" value must be a proper splitio piece of state";
export declare const ERROR_GETT_NO_PARAM_OBJECT = "[ERROR] \"getTreatments\" must be called with a param object containing either splitNames or flagSets properties";
export declare const WARN_FEATUREFLAGS_AND_FLAGSETS = "[WARN]  Both splitNames and flagSets properties were provided. flagSets will be ignored";
